#!/usr/bin/bash

_USER_FLAGS=()
if [[ -f "$1" ]]; then
    while read -r line; do
        if [[ ! "$line" =~ ^[[:space:]]*#.* ]]; then
            _USER_FLAGS+=("$line")
        fi
    done < "$1"
fi

echo "${_USER_FLAGS[@]}"
